# Generated by Django 2.1.5 on 2019-01-23 03:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog5', '0002_auto_20190123_0436'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=300, verbose_name='コメント')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='summary',
            field=models.CharField(default='test', max_length=100, verbose_name='summary'),
        ),
    ]
