# Generated by Django 2.1.5 on 2019-01-23 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog5', '0004_auto_20190123_1805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='email',
            new_name='mailadress',
        ),
    ]
