# Generated by Django 2.1.5 on 2019-01-23 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog5', '0005_auto_20190123_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.PROTECT, to='blog5.Category', verbose_name='カテゴリー'),
        ),
    ]
