# Generated by Django 2.1.5 on 2019-01-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog5', '0006_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(blank=True, to='blog5.Tag', verbose_name='タグ'),
        ),
    ]
