# Generated by Django 2.1.5 on 2019-01-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog5', '0007_article_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='defo', upload_to='documents/'),
        ),
    ]
