# Generated by Django 2.1.5 on 2019-01-24 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog5', '0008_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.PROTECT, to='blog5.Article', verbose_name='親記事'),
        ),
    ]
