# Generated by Django 2.1.5 on 2019-02-25 17:11

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog5', '0009_comment_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=markdownx.models.MarkdownxField(max_length=5000, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='defo.jpg', upload_to='documents/'),
        ),
    ]
